### PR TITLE
fix: Image block DOM clutter, keyboard handling, and copy/paste

### LINKED ISSUE #472: Block Id not found after dragging and resizing image
**Describe the bug**
Block Id not found after dragging and then resizing image.

**To Reproduce**
https://codesandbox.io/p/sandbox/flamboyant-architecture-77jnv3?file=%2Findex.tsx

Step 1: Drag image to any pos
Step 2: Try to resize image

https://github.com/TypeCellOS/BlockNote/assets/48770548/5f7e8dd3-c7d6-4cfa-ae2f-3e061190e69c

https://private-user-images.githubusercontent.com/71827178/289041160-dc554af0-f218-4a6d-b62b-1233d7c29b6e.mov?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMzYzNzUsIm5iZiI6MTcwMjAzNjA3NSwicGF0aCI6Ii83MTgyNzE3OC8yODkwNDExNjAtZGM1NTRhZjAtZjIxOC00YTZkLWI2MmItMTIzM2Q3YzI5YjZlLm1vdj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDExNDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1Njk0NDc4ZjUxN2Y5ZGUyNGIzYWQ4OTQzODkyMWEyMWVlYTY0MmU1MmYwYmM2ODFiMzg0ZTU4NDFlMDE0MWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ua68mKtLMbhrPHIjwlK6019lWBasYX18xf7GgT8sBeE

**Misc**
- Node version: 18.16.0
- Package manager: npm
- Browser: Chrome, Safari

### PR DESCRIPTION
**Pull request by matthewlipski**
This PR makes unused DOM elements from the image block get unmounted when not visible instead of setting `display: none`. Additionally, it fixes keyboard inputs all getting blocked when an image is selected (now only those which insert a character get blocked), and fixes copying for when only an image is selected. The keyboard handling and copy/paste fixes also apply for other block types without inline content.

Closes #472

### CODE REVIEW

File: packages/core/src/api/exporters/copyExtension.ts [hunk 1]
```diff
@@ -17,46 +52,79 @@ export const createCopyToClipboardExtension = <
...
-                  );
-
-                const externalHTMLExporter = createExternalHTMLExporter(
-                  schema,
-                  editor
-                );
-                const externalHTML =
-                  externalHTMLExporter.exportProseMirrorFragment(
-                    selectedFragment
+                // Checks if a `blockContent` node is being copied and expands
```
Comment (YousefED) [inline packages/core/src/api/exporters/copyExtension.ts:64]: As there are no tests specific for this, can you add a comment why we need this? Why did we make this change, i.e.: what scenario would break without expanding the selection in this way?

File: packages/core/src/api/exporters/copyExtension.ts [hunk 2]
```diff
@@ -17,46 +52,79 @@ export const createCopyToClipboardExtension = <
...
                 // TODO: Writing to other MIME types not working in Safari for
                 //  some reason.
                 event.clipboardData!.setData("blocknote/html", internalHTML);
                 event.clipboardData!.setData("text/html", externalHTML);
                 event.clipboardData!.setData("text/plain", plainText);
 
+                // Prevent default PM handler to be called
+                return true;
+              },
+              dragstart(view, event) {
```
Comment (YousefED) [inline packages/core/src/api/exporters/copyExtension.ts:92]: similar to above comment; it's unclear for me why we now also need the dragstart event. What was fixed by this? Can we add a comment to explain for which scenario we need the dragstart event?

**Review by YousefED — COMMENTED** [review]
looks good, but 2 questions that I think should be clarified in code comments

**Review by YousefED — APPROVED** [review]
