### PR TITLE
fix: Scrolling bug when clicking comment marks

### LINKED ISSUE #2158: Comments: Opening a thread trigger a scroll to the top
**Describe the bug**
When we click on a text with a Thread, it triggers a scroll to the top of the page.

It is still doing it on the BN exemple: https://www.blocknotejs.org/examples/collaboration/comments, but not only, we have the problem on our side as well.

This fix didn't seem to work: https://github.com/TypeCellOS/BlockNote/pull/2043

**To Reproduce**

https://github.com/user-attachments/assets/ea3c5033-c54c-4ac6-876c-11d101e0ad86

https://github.com/user-attachments/assets/59e9bf94-4056-4bcf-8241-f02d1eb43c38

**Misc**

- Node version:
- Package manager:
- Browser:
- [x] I'm a [sponsor](https://www.blocknotejs.org/pricing) and would appreciate if you could look into this sooner than later 💖

### PR DESCRIPTION
**Pull request by matthewlipski**
# Summary

This PR fixes a bug which could cause the page to be scrolled to the top when clicking a comment mark. This was because we would attempt to scroll to the floating thread view that pops up after the comment is selected. This would happen before FloatingUI had a chance to position the thread view, so the default position of {0, 0} was used and scrolled to.

This PR removes scrolling to the floating thread view when selecting a comment mark, and instead just scrolls to the mark itself. This makes it reusable for all UI libraries and means we don't have to deal with any FloatingUI weirdness.

Additionally, the `FloatingThreadController` now uses FloatingUI's `autoUpdate` so threads scroll with the editor.

Closes #2158

## Rationale

The scrolling to the top of the page is pretty annoying when trying to view comments.

## Changes

See above.

## Impact

N/A

## Testing

N/A

## Screenshots/Video

N/A

## Checklist

- [X] Code follows the project's coding standards.
- [X] Unit tests covering the new feature have been added.
- [X] All existing tests pass.
- [X] The documentation has been updated to reflect the new feature

### CODE REVIEW

File: packages/mantine/src/comments/Card.tsx
Comment (nperez0111) [inline packages/mantine/src/comments/Card.tsx:1]: Always happy to remove an effect!

File: packages/core/src/extensions/Comments/CommentsPlugin.ts [hunk 1]
```diff
@@ -289,10 +289,11 @@ export class CommentsPlugin extends BlockNoteExtension {
...
       // the editor.
-      (
-        this.editor.prosemirrorView?.domAtPos(selectedThreadPosition.from)
-          .node as Element | undefined
-      )?.scrollIntoView({
+      const node = this.editor.prosemirrorView?.domAtPos(
+        selectedThreadPosition.from,
+      ).node as Element | undefined;
+
+      node?.scrollIntoView({
```
Comment (nperez0111) [inline packages/core/src/extensions/Comments/CommentsPlugin.ts]: Is this not equivalent?

File: packages/core/src/extensions/Comments/CommentsPlugin.ts [hunk 2]
```diff
@@ -245,7 +245,7 @@ export class CommentsPlugin extends BlockNoteExtension {
             );
 
             const threadId = commentMark?.attrs.threadId as string | undefined;
-            self.selectThread(threadId, false);
+            self.selectThread(threadId);
```
Comment (nperez0111) [inline packages/core/src/extensions/Comments/CommentsPlugin.ts:248]: What is the second param? Why is it removed

File: examples/07-collaboration/05-comments/src/style.css
Comment (nperez0111) [inline examples/07-collaboration/05-comments/src/style.css:1]: rm

File: examples/07-collaboration/05-comments/src/App.tsx
Comment (nperez0111) [inline examples/07-collaboration/05-comments/src/App.tsx:1]: rm

File: packages/core/src/extensions/Comments/CommentsPlugin.ts (hunk 2 above)
Comment (matthewlipski) [reply packages/core/src/extensions/Comments/CommentsPlugin.ts:248]: You could set it to false to prevent scrolling to the mark (`scrollToThread`). We did this before and handled the scrolling in the `Card` component instead. Turns out. this was the only place it was set so I removed it outright.

**Comment by nperez0111** [comment]
Unsure if this was introduced @matthewlipski but when I was testing this I ran into this

https://github.com/user-attachments/assets/e22da0ad-3084-49d5-99d4-3dc197f4afcb

Is this what you meant with your comment? Could we do something quick about this? I think it might just be a race condition of the scroll happening after the floating happens (or vice versa?)

**Comment by nperez0111** [comment]
Fantastic, thanks @matthewlipski
