### PR TITLE
fix: Suggestion menu scrolling to selected item

### LINKED ISSUE #773: Suggestion menu does not scroll when using arrow keys
**Describe the bug**
when using up/down arrow keys to select suggestion menu item, the highlighted item does not scroll into view as you move down the list.

**To Reproduce**
reproduced in latest 0.13.4 and homepage demo editor - open suggestion, down arrow to navigate to last item

**Misc**
- Node version:
- Package manager:
- Browser: 
- [ ] I'm a [sponsor](https://github.com/sponsors/YousefED) and would appreciate if you could look into this sooner than later 💖

### PR DESCRIPTION
**Pull request by matthewlipski**
Closes #773

### CODE REVIEW

File: packages/ariakit/src/util/util.tsx [hunk 1]
```diff
@@ -0,0 +1,17 @@
+import { ForwardedRef, MutableRefObject } from "react";
+
+export function mergeRefs<ElementType extends HTMLElement>(
```
Comment (YousefED) [inline packages/ariakit/src/util/util.tsx:3]: I think we already have this function in the core or react package

**Review by YousefED — CHANGES_REQUESTED** [review]
nice! small comments

**Review by YousefED — APPROVED** [review]
great
